### ISSUE TITLE
Yaml conversion inverts -0.0 to 0.0 causing game to crash.

### ISSUE THREAD

**Issue by MaxLastBreath** [ArchLeaders/byml_to_yaml#2]
Specifically converting -0.0 from Rotation: [-0.0, 0.0, -0.0] ends up  looking like Rotation: [0.0, 0.0, 0.0] <-- causes game to crash. Most notably in TOTK -> Banc\MainField\Sky\StartIslandMerge2_Dynamic.bcett.byml.zs files. It also happens in other files, this file in particular had over 4500 instances of it happening.

 Amazing tool BTW. Please fix if possible <3 or add an option to dump to raw text, that would work just as well for me :). I don't know rust otherwise I'd make a pull request :(. I did read some other YAML libs can infact support proper conversion of the numbers. I ended up doing my own conversion in PY to see if that would fix it and it does, however it's very specific for specific objects, therefore now the game crashes elsewhere. Have no way to do it externally :(

**Comment by ArchLeaders** [comment]
Unfortunately, this is an issue with the underlying crate [roead](https://github.com/NiceneNerd/roead). I don't know rust well enough to fix it either, you'll have to make an issue on the [roead](https://github.com/NiceneNerd/roead) repository.
